### PR TITLE
fix: remove duplicate entry from Helm charts 

### LINKED ISSUE #185: Helm - serviceaccounts "cwlwes-autoadmin" already exists
When trying to install the helm chart this error is shown:

```
$ helm uninstall wes-test                                                 
release "wes-test" uninstalled
$ helm upgrade wes-test --install . -f secret-csc-wes-rahtiapp.yaml -f values.yaml 
Release "wes-test" does not exist. Installing it now.
Error: serviceaccounts "cwlwes-autoadmin" already exists
```

**To Reproduce**
1. Install the helm chart
2. See the error of the duplicate accounts

**Expected behavior**

No error should be shown

### PR DESCRIPTION
**Pull request by lvarin**
Resolves #185 (Error: `serviceaccounts "cwlwes-autoadmin" already exists`)

### CODE REVIEW

**Comment by uniqueg** [comment]
@viktoriaas @xhejtman: does this still work for you with @lvarin's change? I'm not the best to do the reviews for these kinda changes....

**Comment by lvarin** [comment]
The chart is broken for Openshift till this is fixed. Not a hurry, but it will make my life easier :)

**Comment by viktoriaas** [comment]
The patch is OK, the bug was related only to OpenShift deployment so it won't break K8S, it can be merged.

**Review by viktoriaas — APPROVED** [review]
Works for K8S after removal

**Pull request merged**
